---
title: LED-circuit informatie
hero_image: images/banner.png
description: De componenten van een eenvoudig circuit en wat ze doen
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: LED-circuit informatie
