---
title: LED 电路信息
hero_image: images/banner.png
description: 简单电路的组成及其作用
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: LED 电路信息
