---
title: Informação do circuito de LED
hero_image: images/banner.png
description: Os componentes de um circuito simples e o que eles fazem
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Informação do circuito de LED
