---
title: Información del circuito LED
hero_image: images/banner.png
description: Los componentes de un circuito simple, y lo que hacen
theme: rojo #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Información del circuito LED
