---
title: Informacje o obwodzie z diodą LED
hero_image: images/banner.png
description: Elementy prostego obwodu i ich działanie
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Informacje o obwodzie z diodą LED
