---
title: LED circuit information
hero_image: images/banner.png
description: The components of a simple circuit, and what they do
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: LED circuit information
