---
title: Informations sur le circuit LED
hero_image: images/banner.png
description: Les composants d'un circuit simple et ce qu'ils font
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Informations sur le circuit LED
